theme = "catppuccin_mocha_hard"

[editor]
scrolloff = 3
color-modes = true
line-number = "relative"
idle-timeout = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
